maidsafe/maidsafe.github.io

Gruntfile.js
package.json

Removed plugins regarde and grunt-contrib-livereload. Instead switched to watch and connect-reload

MAID-690-PR_utility_OSX_support

---

Gruntfile.js
grunt_helper/github.cli.js
grunt_helper/github.js

Instead of using the branch name as the local brach, now picking the PR title for creating  the local branch

Maid 856 grunt pr local branch issue

---

app/js/roadmap.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/52)

fix broken pan on zoom

---

app/documents.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/57)

Documents Page Layout updation

---

app/careers.html
app/css/styles.css

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/58)

MAID-1284 update careers

---

app/_includes/html/footer.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/66)

MAID-1384 Remove invalid links from footer

---

Gruntfile.js
app/css/app.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/index.html
app/js/app.js

End user site home page issue fixed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/65)

MAID-1372 End user site home page

---

app/css/app.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/js/app.js
app/safecoin.html

End user site - safecoin page issues fixed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/69)

MAID-1375 End user site safecoin page

---

app/css/app.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/support.html

End user site - support page issues fixed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/70)

MAID-1376 End user site support page

---

app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/img/faq_down.svg
app/img/faq_up.svg
app/js/app.js

Changes in FAQ page implemented.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/71)

MAID-1468 Changes in FAQ page

---

app/css/large_screen_media.css
app/css/small_screen_media.css

Implemented general fixes in header primary nav and footer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/72)

MAID-1467 General fixes in header and footer

---

app/careers.html
npm-debug.log

MAID-1483 Career page updated for Rust Engineer
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/78)

MAID-1483 Career page updated for Rust Engineer

---

app/support.html

FAQ content replaced.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/76)

MAID-1470 Replace content FAQ content

---

app/_includes/html/footer.html
app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css

MAID-1486 Redesigned footer implemented
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/82)

MAID-1486 Implement new redesigned footer

---

app/css/app.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/support.html

MAID-1479 Faq page implemented
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/83)

MAID-1479 Implement new faq page

---

app/_includes/html/header.html
app/css/app.css
app/faq.html
app/js/app.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/91)

Maid 1489 changes to nav bar

---

app/css/app.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/index.html
app/js/app.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/92)

Maid 1491 add intro video

---

app/company.html
app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/93)

Maid 1496 Increase margin between footer and content

---

app/_includes/html/footer.html
app/company.html
app/contact.html
app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/js/app.js

MAID-1493 Implement contact page
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/89)

MAID-1493 Implement contact page

---

app/_includes/html/footer.html
app/company.html
app/contact.html
app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css
app/js/app.js
app/rust_engineer.html

MAID-1495 Implement Job Spec Page
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/90)

MAID-1495 Implement Job Spec Page

---

app/css/app.css
app/index.html

MAID-1498 Implement changes to homepage for user site
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/94)

MAID-1498 Implement changes to homepage for user site

---

app/features.html
app/index.html
app/safecoin.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/99)

MAID-1504 text edits

---

app/_includes/html/footer.html
app/company.html
app/faq.html
app/features.html
app/index.html
app/safecoin.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/101)

Maid 1505 text edits

---

app/_includes/html/footer.html
app/css/app.css
app/disclaimer.html
app/rust_engineer.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/100)

MAID-1506 disclaimer changes

---

app/_includes/html/footer.html
app/css/app.css
app/css/desktop_and_laptop_media.css
app/css/large_screen_media.css
app/css/mobile_media.css
app/css/small_screen_media.css
app/css/tablet_media.css

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/105)

Maid 1509 - Implement further changes to the footer

---

app/_includes/html/footer.html
app/js/app.js

Footer links corrected and the header styling issue fixed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/107)

Dist mode fixes

---

app/_includes/html/header.html
app/credits.html
app/css/mobile_media.css
app/index.html

Link redirection and overlap issue fixed on home page
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/108)

Hope page fixes

---

app/company.html
app/faq.html
app/features.html
app/index.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/112)

typo clean up

---

app/index.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/117)

Maid 1512 - Text update

---

app/css/app.css
app/js/app.js
app/js/jsonData.js

Company page style fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/123)

Company page style fixes

---

.travis.yml
app/data/roadmapData.json

Mobile client added under client
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/125)

Launcher client and Launcher ARM devices added under client

---

app/css/app.css
app/img/roadmap_legends/key_complete.svg
app/img/roadmap_legends/key_in_progress.svg
app/img/roadmap_legends/key_planned.svg
app/js/roadmap.js
app/roadmap.html

Roadmap legends added and performance issue fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/maidsafe.github.io/128)

Roadmap legends added and performance issue fixed
